name: Populate Depot JSON

on:
  # runs when this repository's releases are modified
  release:
  # allows for manual dispatching of the workflow
  workflow_dispatch:

jobs:
  populate:
    runs-on: ubuntu-latest
    permissions:
      # permits reading of releases and writing to the depot branch
      contents: write
    steps:
      - name: Populate depot
        uses: jerrylum/pros-depot@main
        id: depot
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: depot
          target_path: depot.json
          push: false
      - name: Print depot file
        run: |
          echo ${{ env.depot }} > depot.json
          cat depot.json
        env:
          depot: ${{ steps.depot.outputs.depot }}
