name: Add download link to pull request
on:
  workflow_run:
    workflows: ["Build Template"]
    types: [completed]
jobs:
  pr_comment:
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          # This snippet is public-domain, taken from
          # https://github.com/oprypin/nightly.link/blob/master/.github/workflows/pr-comment.yml
          script: |
            async function upsertComment(owner, repo, issue_number, purpose, old_body, insertion) {    
              const marker = `\r\n<!-- DO NOT REMOVE!! -->\r\n<!-- bot: ${purpose} -->\r\n`;

              const old_marker = new RegExp(marker.replace("\r\n", "\r?\n")).exec(old_body)?.[0] ?? marker;
              
              const new_body = old_body.split(old_marker)[0] + marker + insertion;
              await github.rest.pulls.update({
                owner: owner,
                repo: repo,
                pull_number: issue_number,
                body: new_body
              });
            }

            const {owner, repo} = context.repo;
            const run_id = ${{github.event.workflow_run.id}};

            const pull_head_sha = '${{github.event.workflow_run.head_sha}}';

            const pull_requests = ${{ toJSON(github.event.workflow_run.pull_requests) }};
            if (!pull_requests.length) {
              return core.error("This workflow doesn't match any pull requests!");
            }
            const issue_number = pull_requests[0].number;
            const old_body = pull_requests[0].body;

            let old_sha = /\<\!-- commit-sha: (?<sha>[a-z0-9]+) --\>/i.exec(old_body)?.groups?.sha
            if (old_sha != undefined && pull_head_sha == old_sha) return core.error("Comment is already up-to-date!")

            const artifacts = await github.paginate(
              github.rest.actions.listWorkflowRunArtifacts, {owner, repo, run_id});
            if (!artifacts.length) {
              return core.error(`No artifacts found, perhaps Build Template was skipped`);
            }
            const template = artifacts[0];

            let insertion = `<!-- commit-sha: ${pull_head_sha} -->
            ## Download the template for this pull request:

            > [!NOTE]
            > This is auto generated from [\`${{ github.workflow }}\`](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - via manual download: [${template.name}.zip](https://nightly.link/${owner}/${repo}/actions/artifacts/${template.id}.zip)
            - via PROS Integrated Terminal:
            \`\`\`
            curl -o ${template.name}.zip https://nightly.link/${owner}/${repo}/actions/artifacts/${template.id}.zip;
            pros c fetch ${template.name}.zip;
            pros c apply ${template.name};
            rm ${template.name}.zip;
            \`\`\``;

            core.info(`Review thread message body: \n${insertion}`);

            await upsertComment(owner, repo, issue_number,
              "nightly-link", old_body, insertion);
