name: Build Template

env:
  PROS_CLI_VERSION: "3.5.4"

on:
  push:
    branches: "**"
    tags:
      - "v*" # Trigger on version tags
  pull_request:
    branches: "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build information
        id: build-info
        run: |
          version_core=$(awk -F'=' '/^VERSION:=/{print $2}' Makefile)
          library_name=$(awk -F'=' '/^LIBNAME:=/{print $2}' Makefile)

          # If a new tag is pushed
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Remove the 'v' prefix from the tag version
            tag_version="${GITHUB_REF#refs/tags/v}"
            # Check if version_core is the same as tag_version; if not, fail
            if [[ "${version_core}" != "${tag_version}" ]]; then
              echo "The version in the Makefile does not match the pushed tag version: ${version_core} != ${tag_version}"
              exit 1
            fi

            # Set the version to the version core without the 'v' prefix and the build identifier
            version=${version_core}
          else
            # Obtain build identifier by head SHA if it is not empty; otherwise, use $GITHUB_SHA
            # $GITHUB_SHA might be the merge commit SHA, which is not preferred
            # See: https://stackoverflow.com/questions/68061051/get-commit-sha-in-github-actions
            # This should also work for forked pull requests
            if [[ -n "${{ github.event.pull_request.head.sha }}" ]]; then
              SHA="${{ github.event.pull_request.head.sha }}"
            else
              SHA="${GITHUB_SHA}"
            fi
            build_id=${SHA:0:6}

            # Set the version to the tag version plus the build identifier
            version="${version_core}+${build_id}"
          fi
          artifact_name="${library_name}@${version}"

          # Use tee to write to the output file and stdout
          echo "version_core=${version_core}" | tee -a $GITHUB_OUTPUT
          echo "library_name=${library_name}" | tee -a $GITHUB_OUTPUT
          echo "version=${version}" | tee -a $GITHUB_OUTPUT
          echo "artifact_name=${artifact_name}" | tee -a $GITHUB_OUTPUT

      # This is a faster alternative to fiam/arm-none-eabi-gcc@v1
      - name: Install ARM Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.8.1
        with:
          release: "10.3-2021.10" # Same with purduesigbots/VOSS

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Cache pip packages
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pros-cli-${{ env.PROS_CLI_VERSION }}-${{ runner.os }}-${{ runner.arch }}
          restore-keys: |
            pros-cli-${{ env.PROS_CLI_VERSION }}-${{ runner.os }}-${{ runner.arch }}

      - name: Install PROS CLI
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: pip install pros-cli==${{ env.PROS_CLI_VERSION }}

      - name: Print PROS CLI Version
        run: pros --version

      - name: Build project
        run: pros make all

      - name: Create template
        run: pros make template VERSION=${{ steps.build-info.outputs.version }}

      # First unzip the artifact zip file to a directory with the same name as the artifact
      - name: Unzip Artifact
        run: unzip ${{ steps.build-info.outputs.artifact_name }}.zip -d ${{ steps.build-info.outputs.artifact_name }}

      # Upload the artifact directory, GitHub Actions will zip it up again and upload it as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-info.outputs.artifact_name }}
          path: ${{ steps.build-info.outputs.artifact_name }}
          if-no-files-found: error
          retention-days: 89
