name: Build Template

env:
  PROS_CLI_VERSION: "3.5.4"

on:
  push:
    branches: "**"
    tags:
      - "v*" # Trigger on version tags
  pull_request:
    branches: "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build template
        id: build
        uses: jerrylum/pros-build@main
        with:
          build_args: "quick template -j" # -j enables multi-threading

      - name: Copy files to artifact directory
        run: |
          echo "${{ steps.build.outputs.version }}" > ${{ env.INCLUDE_DIR }}/VERSION
          cp README.md ${{ env.INCLUDE_DIR }}
          cp LICENSE ${{ env.INCLUDE_DIR }}
        env:
          INCLUDE_DIR: ${{ steps.build.outputs.artifact_path }}/include/my-library

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.artifact_name }}
          path: ${{ steps.build.outputs.artifact_path }}
