name: Build Template

on:
  push:
    branches: "**"
    tags:
      - "v*" # Trigger on version tags
  pull_request:
    branches: "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build tests
        id: build-tests
        uses: jerrylum/pros-build@v2.0.0
        with:
          build_args: "all -j EXTRA_CXXFLAGS=-DUNIT_TEST" # -j enables multi-threading

      - name: Run tests
        id: run-tests
        timeout-minutes: 1
        uses: jerrylum/vex-v5-qemu-gh-action@main

      - name: Clean build results
        id: clean-tests
        uses: jerrylum/pros-build@v2.0.0
        with:
          build_args: "clean" # it might be necessary to clean the build results

      - name: Build template
        id: build
        uses: jerrylum/pros-build@v2.0.0
        with:
          build_args: "quick template -j" # -j enables multi-threading

      - name: Copy files to artifact directory
        run: |
          echo "${{ steps.build.outputs.version }}" > "${{ env.INCLUDE_DIR }}/VERSION"
          cp README.md "${{ env.INCLUDE_DIR }}"
          cp LICENSE "${{ env.INCLUDE_DIR }}"
        env:
          INCLUDE_DIR: ${{ steps.build.outputs.artifact_path }}/include/my-library

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.artifact_name }}
          path: ${{ steps.build.outputs.artifact_path }}
