name: Build Template

on:
  push:
    branches: "**"
    tags:
      - "v*" # Trigger on version tags
  pull_request:
    branches: "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Determine build type
        id: build-type
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "type=release" >> $GITHUB_OUTPUT
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            echo "type=pr" >> $GITHUB_OUTPUT
            echo "pr_num=${GITHUB_REF#refs/pull/}" >> $GITHUB_OUTPUT
            echo "pr_num=${pr_num%/merge}" >> $GITHUB_OUTPUT
          else
            echo "type=push" >> $GITHUB_OUTPUT
          fi

      - name: Read project makefile
        id: read-makefile
        run: |
          echo "version_core=$(awk -F'=' '/^VERSION:=/{print $2}' Makefile)" >> $GITHUB_OUTPUT
          echo "library_name=$(awk -F'=' '/^LIBNAME:=/{print $2}' Makefile)" >> $GITHUB_OUTPUT

