name: Build Template

env:
  PROS_CLI_VERSION: "3.5.4"

on:
  push:
    branches: "**"
    tags:
      - "v*" # Trigger on version tags
  pull_request:
    branches: "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build information
        id: build-info
        run: |
          version_core=$(awk -F'=' '/^VERSION:=/{print $2}' Makefile)
          library_name=$(awk -F'=' '/^LIBNAME:=/{print $2}' Makefile)

          # If a new tag is pushed
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Remove the 'v' prefix from the tag version
            tag_version="${GITHUB_REF#refs/tags/v}"
            # Check if version_core is the same as tag_version; if not, fail
            if [[ "${version_core}" != "${tag_version}" ]]; then
              echo "The version in the Makefile does not match the pushed tag version: ${version_core} != ${tag_version}"
              exit 1
            fi

            # Set the version to the version core without the 'v' prefix and the build identifier
            version=${version_core}
          else
            # Obtain build identifier by head SHA if it is not empty; otherwise, use $GITHUB_SHA
            # $GITHUB_SHA might be the merge commit SHA, which is not preferred
            # See: https://stackoverflow.com/questions/68061051/get-commit-sha-in-github-actions
            # This should also work for forked pull requests
            if [[ -n "${{ github.event.pull_request.head.sha }}" ]]; then
              SHA="${{ github.event.pull_request.head.sha }}"
            else
              SHA="${GITHUB_SHA}"
            fi
            build_id=${SHA:0:6}

            # Set the version to the tag version plus the build identifier
            version="${version_core}+${build_id}"
          fi
          artifact_name="${library_name}@${version}"

          # Use tee to write to the output file and stdout
          echo "version_core=${version_core}" | tee -a $GITHUB_OUTPUT
          echo "library_name=${library_name}" | tee -a $GITHUB_OUTPUT
          echo "version=${version}" | tee -a $GITHUB_OUTPUT
          echo "artifact_name=${artifact_name}" | tee -a $GITHUB_OUTPUT

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Cache ARM Toolchain and PROS CLI
        id: cache-toolchain-and-pros-cli
        uses: actions/cache@v4
        with:
          path: |
            $HOME/gcc-arm-none-eabi/bin
            $HOME/.local/lib/python3.9/site-packages
            $HOME/.local/bin
          key: toolchain-and-pros-cli-${{ runner.os }}-${{ runner.arch }}
          restore-keys: |
            toolchain-and-pros-cli-${{ runner.os }}-${{ runner.arch }}

      - name: Install ARM Toolchain
        if: steps.cache-toolchain-and-pros-cli.outputs.cache-hit != 'true'
        run: |
          wget --no-verbose https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 -O /tmp/gcc-arm-none-eabi.tar.bz2
          mkdir -p $HOME/gcc-arm-none-eabi
          tar -xjf /tmp/gcc-arm-none-eabi.tar.bz2 -C $HOME/gcc-arm-none-eabi --strip-components=1
          echo "Adding ARM toolchain to PATH"
          echo "$HOME/gcc-arm-none-eabi/bin" >> $GITHUB_PATH

        # This is a faster alternative to fiam/arm-none-eabi-gcc@v1 and carlosperate/arm-none-eabi-gcc-action

      - name: Install PROS CLI
        if: steps.cache-toolchain-and-pros-cli.outputs.cache-hit != 'true'
        run: pip install --user pros-cli==${{ env.PROS_CLI_VERSION }}

      - name: Print PROS CLI Version
        run: pros --version

      - name: Build project
        run: pros make all

      - name: Create template
        run: pros make template VERSION=${{ steps.build-info.outputs.version }}

      # First unzip the artifact zip file to a directory with the same name as the artifact
      - name: Unzip Artifact
        run: unzip ${{ steps.build-info.outputs.artifact_name }}.zip -d ${{ steps.build-info.outputs.artifact_name }}

      # Upload the artifact directory, GitHub Actions will zip it up again and upload it as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-info.outputs.artifact_name }}
          path: ${{ steps.build-info.outputs.artifact_name }}
          if-no-files-found: error
          retention-days: 89
